spring.mongodb.uri=${MONGODB_URI:mongodb+srv://nimesh:Nimesh25@cluster0.a85pimh.mongodb.net/interntrack?appName=Cluster0}

jwt.secret=${JWT_SECRET:Y2hhdG1hbmFnZW1lbnRhcHBsaWNhdGlvbnNlY3JldGtleWZvcmp3dHRva2VuZ2VuZXJhdGlvbg==}
jwt.expiration=${JWT_EXPIRATION:86400000}

file.upload-dir=${FILE_UPLOAD_DIR:uploads/profile-images}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB