spring.mongodb.uri=mongodb+srv://nimesh:Nimesh25@cluster0.a85pimh.mongodb.net/interntrack?appName=Cluster0

jwt.secret=Y2hhdG1hbmFnZW1lbnRhcHBsaWNhdGlvbnNlY3JldGtleWZvcmp3dHRva2VuZ2VuZXJhdGlvbg==
jwt.expiration=86400000